export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR'
export const SUCCESS_CHANGE_C = 'SUCCESS_CREATE_C'
export const ERROR_CHANGE_C = 'ERROR_CREATE_C'